### ISSUE TITLE
Missing class `parse` method?

### ISSUE THREAD

**Issue by jarsen** [rmosolgo/lingo#4]
This is a question. I'm just getting started with Crystal so it is likely user error on my part, but I can't for the life of me get my own parser or the example parser to compile in a new project. The compiler complains about `undefined method 'parse'`. I did a `shards install` and the shard is there, so I assume something is going on and the macros aren't getting triggered or something to write the `parse` method. Any hints would be greatly appreciated, I'm really excited this looks like awesome work :)

Here's what I have:

```
require "Readline"
require "Lingo"

module Banish
  VERSION = "0.1.0"
end

loop do
  cmdline = Readline.readline(">> ", add_history=true)
  next if cmdline.nil?
  ast = CmdLineParser.parse(cmdline)
  puts ast
end

class CmdLineParser < Lingo::Parser
  rule(:cmdline) { command }
  rule(:command) { arg.repeat }
  rule(:arg) { match(/\S/).repeat >> space? }

  rule(:space?) { space.maybe }
  rule(:space) { match(/\s/).repeat }

  root(:cmdline)
end
```

**Comment by jarsen** [comment]
Coming back to it, I got the sample `RoadParser` to run by calling `parse` as an instance method on a new instance as opposed to a class method (doing the same on my own revealed problems with the rules in my own sample). Not sure if the readme is out of date or I am missing something. Happy to do a PR to update the documentation if the case of the former if that would be helpful.

**Comment by rmosolgo** [comment]
Woops! Yes, a PR to fix the docs or add that class method would be very welcome!
